Enable more compiler warnings and fix results
Add some basic flags compatible with gcc and clang, and fix the resulting errors:

```
src/_time_machine.c:519:27: error: cast from 'PyCFunction' (aka 'struct _object *(*)(struct _object *, struct _object *)') to 'PyCFunctionFastWithKeywords' (aka 'struct _object
*(*)(struct _object *, struct _object *const *, long, struct _object *)') converts to incompatible function type [-Werror,-Wcast-function-type-mismatch]
  519 |     state->original_now = (PyCFunctionFastWithKeywords)datetime_datetime_now->m_ml->ml_meth;
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/_time_machine.c:523:44: error: cast from 'PyObject *(*)(PyTypeObject *, PyObject *const *, Py_ssize_t, PyObject *)' (aka 'struct _object *(*)(struct _typeobject *,
struct _object *const *, long, struct _object *)') to 'PyCFunction' (aka 'struct _object *(*)(struct _object *, struct _object *)') converts to incompatible function type
[-Werror,-Wcast-function-type-mismatch]
  523 |     datetime_datetime_now->m_ml->ml_meth = (PyCFunction)_time_machine_now;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/_time_machine.c:620:9: error: cast from 'PyObject *(*)(PyObject *, PyObject *const *, Py_ssize_t, PyObject *)' (aka 'struct _object *(*)(struct _object *, struct
_object *const *, long, struct _object *)') to 'PyCFunction' (aka 'struct _object *(*)(struct _object *, struct _object *)') converts to incompatible function type
[-Werror,-Wcast-function-type-mismatch]
  620 |         (PyCFunction)_time_machine_original_now,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/_time_machine.c:697:1: error: no previous prototype for function 'PyInit__time_machine' [-Werror,-Wmissing-prototypes]
  697 | PyInit__time_machine(void)
      | ^
src/_time_machine.c:696:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  696 | PyMODINIT_FUNC
      | ^
/Users/chainz/.local/share/uv/python/cpython-3.13.6-macos-aarch64-none/include/python3.13/exports.h:103:58: note: expanded from macro 'PyMODINIT_FUNC'
  103 | #               define PyMODINIT_FUNC Py_EXPORTED_SYMBOL PyObject*
      |                                                          ^
4 errors generated.
error: command '/usr/bin/cc' failed with exit code 1
```